export const MARIO_KART_THEMES = {
    mario: {
        id: "mario",
        name: "Mario",
        type: "Bilanciato",
        description: "Ottimo controllo e velocità media. Ideale per ogni situazione.",
        colors: { primary: "#E52521", secondary: "#00512C", accent: "#FCD34D", bgDark: "#1A1010", bgLight: "#FEE2E2" },
        tailwind: {
            bg: "bg-[#E52521]",
            text: "text-[#E52521]",
            border: "border-[#E52521]",
            badge: "bg-[#E52521]/15 text-[#E52521] dark:bg-[#E52521]/20 dark:text-[#EF4444]",
            ring: "focus:ring-[#E52521]",
            bgSoft: "bg-[#E52521]/20",
            textStrong: "text-[#00512C]",
            borderSoft: "border-[#E52521]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: {
            emblemUrl: "https://www.sprites-resource.com/resources/sheets/17392/emblem_mario.png",
            spriteSheetUrl: "https://www.sprites-resource.com/resources/sheets/4/3688.png",
        },
    },
    luigi: {
        id: "luigi",
        name: "Luigi",
        type: "Bilanciato",
        description: "Statistiche simili a Mario, ma con una trazione leggermente superiore.",
        colors: { primary: "#00B239", secondary: "#001B44", accent: "#FCD34D", bgDark: "#0B150F", bgLight: "#DCFCE7" },
        tailwind: {
            bg: "bg-[#00B239]",
            text: "text-[#00B239]",
            border: "border-[#00B239]",
            badge: "bg-[#00B239]/15 text-[#00B239] dark:bg-[#00B239]/20 dark:text-[#4ADE80]",
            ring: "focus:ring-[#00B239]",
            bgSoft: "bg-[#00B239]/20",
            textStrong: "text-[#001B44]",
            borderSoft: "border-[#00B239]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: {
            emblemUrl: "https://www.sprites-resource.com/resources/sheets/17392/emblem_luigi.png",
            spriteSheetUrl: "https://www.sprites-resource.com/resources/sheets/4/3689.png",
        },
    },
    yoshi: {
        id: "yoshi",
        name: "Yoshi",
        type: "Leggero",
        description: "Accelerazione eccezionale e massima reattività in curva (Drift).",
        colors: { primary: "#22C55E", secondary: "#F97316", accent: "#FFFFFF", bgDark: "#0A140F", bgLight: "#E0F2FE" },
        tailwind: {
            bg: "bg-[#22C55E]",
            text: "text-[#22C55E]",
            border: "border-[#22C55E]",
            badge: "bg-[#22C55E]/15 text-[#16A34A] dark:bg-[#22C55E]/20 dark:text-[#4ADE80]",
            ring: "focus:ring-[#22C55E]",
            bgSoft: "bg-[#22C55E]/20",
            textStrong: "text-[#F97316]",
            borderSoft: "border-[#22C55E]/20",
        },
        animationClass: "animate-drift-fast",
        assets: {
            emblemUrl: "https://www.sprites-resource.com/resources/sheets/17392/emblem_yoshi.png",
            spriteSheetUrl: "https://www.sprites-resource.com/resources/sheets/4/3691.png",
        },
    },
    peach: {
        id: "peach",
        name: "Peach",
        type: "Leggero",
        description: "Veicolo leggero con ottima accelerazione, soffre gli scontri pesanti.",
        colors: { primary: "#FF8BB2", secondary: "#38BDF8", accent: "#EAB308", bgDark: "#1A0F13", bgLight: "#FCE7F3" },
        tailwind: {
            bg: "bg-[#FF8BB2]",
            text: "text-[#FF8BB2]",
            border: "border-[#FF8BB2]",
            badge: "bg-[#FF8BB2]/15 text-[#DB2777] dark:bg-[#FF8BB2]/20 dark:text-[#F472B6]",
            ring: "focus:ring-[#FF8BB2]",
            bgSoft: "bg-[#FF8BB2]/20",
            textStrong: "text-[#38BDF8]",
            borderSoft: "border-[#FF8BB2]/20",
        },
        animationClass: "animate-float-elegant",
        assets: {
            emblemUrl: "https://www.sprites-resource.com/resources/sheets/17392/emblem_peach.png",
            spriteSheetUrl: "https://www.sprites-resource.com/resources/sheets/4/3690.png",
        },
    },
    toad: {
        id: "toad",
        name: "Toad",
        type: "Leggero",
        description: "Accelerazione fulminea ma velocità massima ridotta. Ideale per piste tortuose.",
        colors: { primary: "#1E65A7", secondary: "#CE1126", accent: "#FFFFFF", bgDark: "#0C1625", bgLight: "#E0F2FE" },
        tailwind: {
            bg: "bg-[#1E65A7]",
            text: "text-[#1E65A7]",
            border: "border-[#1E65A7]",
            badge: "bg-[#1E65A7]/15 text-[#1E65A7] dark:bg-[#1E65A7]/20 dark:text-[#60A5FA]",
            ring: "focus:ring-[#1E65A7]",
            bgSoft: "bg-[#1E65A7]/20",
            textStrong: "text-[#CE1126]",
            borderSoft: "border-[#1E65A7]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: {
            emblemUrl: "https://www.sprites-resource.com/resources/sheets/17392/emblem_toad.png",
            spriteSheetUrl: "https://www.sprites-resource.com/resources/sheets/4/3692.png",
        },
    },
    bowser: {
        id: "bowser",
        name: "Bowser",
        type: "Pesante",
        description: "Velocità massima elevatissima ma accelerazione lenta. Domina nei rettilinei.",
        colors: { primary: "#D4A017", secondary: "#8B0000", accent: "#FF6B35", bgDark: "#1A0A0A", bgLight: "#FFF8E1" },
        tailwind: {
            bg: "bg-[#D4A017]",
            text: "text-[#D4A017]",
            border: "border-[#D4A017]",
            badge: "bg-[#D4A017]/15 text-[#8B0000] dark:bg-[#D4A017]/20 dark:text-[#FCD34D]",
            ring: "focus:ring-[#D4A017]",
            bgSoft: "bg-[#D4A017]/20",
            textStrong: "text-[#8B0000]",
            borderSoft: "border-[#D4A017]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: {
            emblemUrl: "https://www.sprites-resource.com/resources/sheets/17392/emblem_bowser.png",
            spriteSheetUrl: "https://www.sprites-resource.com/resources/sheets/4/3700.png",
        },
    },
    "donkey kong": {
        id: "donkey_kong",
        name: "Donkey Kong",
        type: "Pesante",
        description: "Potenza bruta e derapate devastanti. Perfetto per piloti aggressivi.",
        colors: { primary: "#6B3A1F", secondary: "#CC0000", accent: "#F5DEB3", bgDark: "#120A06", bgLight: "#FFF3E0" },
        tailwind: {
            bg: "bg-[#6B3A1F]",
            text: "text-[#6B3A1F]",
            border: "border-[#6B3A1F]",
            badge: "bg-[#6B3A1F]/15 text-[#CC0000] dark:bg-[#6B3A1F]/20 dark:text-[#FCA5A5]",
            ring: "focus:ring-[#6B3A1F]",
            bgSoft: "bg-[#6B3A1F]/20",
            textStrong: "text-[#CC0000]",
            borderSoft: "border-[#6B3A1F]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: {
            emblemUrl: "https://www.sprites-resource.com/resources/sheets/17392/emblem_donkey_kong.png",
            spriteSheetUrl: "https://www.sprites-resource.com/resources/sheets/4/3702.png",
        },
    },
    waluigi: {
        id: "waluigi",
        name: "Waluigi",
        type: "Bilanciato",
        description: "Statistiche equilibrate con una propensione per le derapate lunghe.",
        colors: { primary: "#6A0DAD", secondary: "#2D004F", accent: "#FFD700", bgDark: "#0E0515", bgLight: "#F3E5F5" },
        tailwind: {
            bg: "bg-[#6A0DAD]",
            text: "text-[#6A0DAD]",
            border: "border-[#6A0DAD]",
            badge: "bg-[#6A0DAD]/15 text-[#6A0DAD] dark:bg-[#6A0DAD]/20 dark:text-[#C084FC]",
            ring: "focus:ring-[#6A0DAD]",
            bgSoft: "bg-[#6A0DAD]/20",
            textStrong: "text-[#2D004F]",
            borderSoft: "border-[#6A0DAD]/20",
        },
        animationClass: "animate-waluigi-wobble",
        assets: {
            emblemUrl: "https://www.sprites-resource.com/resources/sheets/17392/emblem_waluigi.png",
            spriteSheetUrl: "https://www.sprites-resource.com/resources/sheets/4/3701.png",
        },
    },

    // ── MK8 Deluxe ───────────────────────────────────────────────────────────
    wario: {
        id: "wario",
        name: "Wario",
        type: "Pesante",
        description: "Velocità massima elevata e peso schiacciante. Avido quanto efficace sui rettilinei.",
        colors: { primary: "#D4AC0D", secondary: "#5B2D8E", accent: "#FFD700", bgDark: "#1A1200", bgLight: "#FFFDE7" },
        tailwind: {
            bg: "bg-[#D4AC0D]",
            text: "text-[#D4AC0D]",
            border: "border-[#D4AC0D]",
            badge: "bg-[#D4AC0D]/15 text-[#5B2D8E] dark:bg-[#D4AC0D]/20 dark:text-[#FDE047]",
            ring: "focus:ring-[#D4AC0D]",
            bgSoft: "bg-[#D4AC0D]/20",
            textStrong: "text-[#5B2D8E]",
            borderSoft: "border-[#D4AC0D]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: null,
    },
    rosalina: {
        id: "rosalina",
        name: "Rosalina",
        type: "Medio",
        description: "Governatrice delle stelle con una guida fluida ed elegante. Ottimo in velocità.",
        colors: { primary: "#5BA4CF", secondary: "#1A3A5C", accent: "#E8D5F5", bgDark: "#0A1525", bgLight: "#EFF8FF" },
        tailwind: {
            bg: "bg-[#5BA4CF]",
            text: "text-[#5BA4CF]",
            border: "border-[#5BA4CF]",
            badge: "bg-[#5BA4CF]/15 text-[#1A3A5C] dark:bg-[#5BA4CF]/20 dark:text-[#93C5FD]",
            ring: "focus:ring-[#5BA4CF]",
            bgSoft: "bg-[#5BA4CF]/20",
            textStrong: "text-[#1A3A5C]",
            borderSoft: "border-[#5BA4CF]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },
    daisy: {
        id: "daisy",
        name: "Daisy",
        type: "Medio",
        description: "Energica e combattiva. Accelerazione vivace e grande resistenza alle collisioni.",
        colors: { primary: "#F59E0B", secondary: "#EA580C", accent: "#FEF3C7", bgDark: "#1C1000", bgLight: "#FFFBEB" },
        tailwind: {
            bg: "bg-[#F59E0B]",
            text: "text-[#F59E0B]",
            border: "border-[#F59E0B]",
            badge: "bg-[#F59E0B]/15 text-[#EA580C] dark:bg-[#F59E0B]/20 dark:text-[#FCD34D]",
            ring: "focus:ring-[#F59E0B]",
            bgSoft: "bg-[#F59E0B]/20",
            textStrong: "text-[#EA580C]",
            borderSoft: "border-[#F59E0B]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: null,
    },
    "bowser jr.": {
        id: "bowser_jr",
        name: "Bowser Jr.",
        type: "Leggero",
        description: "Figlio di Bowser, piccolo ma imprevedibile. Accelerazione sorprendente per un villain.",
        colors: { primary: "#F97316", secondary: "#7C2D12", accent: "#FEF08A", bgDark: "#1A0800", bgLight: "#FFF7ED" },
        tailwind: {
            bg: "bg-[#F97316]",
            text: "text-[#F97316]",
            border: "border-[#F97316]",
            badge: "bg-[#F97316]/15 text-[#7C2D12] dark:bg-[#F97316]/20 dark:text-[#FB923C]",
            ring: "focus:ring-[#F97316]",
            bgSoft: "bg-[#F97316]/20",
            textStrong: "text-[#7C2D12]",
            borderSoft: "border-[#F97316]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: null,
    },
    "king boo": {
        id: "king_boo",
        name: "King Boo",
        type: "Pesante",
        description: "Spettrale e imponente. Gestione fluida nonostante il peso, terrificante in curva.",
        colors: { primary: "#9333EA", secondary: "#3B0764", accent: "#F5F3FF", bgDark: "#0D0020", bgLight: "#F5F3FF" },
        tailwind: {
            bg: "bg-[#9333EA]",
            text: "text-[#9333EA]",
            border: "border-[#9333EA]",
            badge: "bg-[#9333EA]/15 text-[#3B0764] dark:bg-[#9333EA]/20 dark:text-[#C084FC]",
            ring: "focus:ring-[#9333EA]",
            bgSoft: "bg-[#9333EA]/20",
            textStrong: "text-[#3B0764]",
            borderSoft: "border-[#9333EA]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },
    "dry bowser": {
        id: "dry_bowser",
        name: "Dry Bowser",
        type: "Pesante",
        description: "L'ossuto re dei Koopa. Velocità massima da capogiro, implacabile sui lunghi rettilinei.",
        colors: { primary: "#9CA3AF", secondary: "#1F2937", accent: "#FEF3C7", bgDark: "#111827", bgLight: "#F9FAFB" },
        tailwind: {
            bg: "bg-[#9CA3AF]",
            text: "text-[#9CA3AF]",
            border: "border-[#9CA3AF]",
            badge: "bg-[#9CA3AF]/15 text-[#1F2937] dark:bg-[#9CA3AF]/20 dark:text-[#D1D5DB]",
            ring: "focus:ring-[#9CA3AF]",
            bgSoft: "bg-[#9CA3AF]/20",
            textStrong: "text-[#1F2937]",
            borderSoft: "border-[#9CA3AF]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: null,
    },
    "metal mario": {
        id: "metal_mario",
        name: "Metal Mario",
        type: "Pesante",
        description: "Mario in versione metallica: peso massiccio, velocità di punta elevata. Impenetrabile agli urti.",
        colors: { primary: "#64748B", secondary: "#1E3A5F", accent: "#E0F2FE", bgDark: "#0F172A", bgLight: "#F1F5F9" },
        tailwind: {
            bg: "bg-[#64748B]",
            text: "text-[#64748B]",
            border: "border-[#64748B]",
            badge: "bg-[#64748B]/15 text-[#1E3A5F] dark:bg-[#64748B]/20 dark:text-[#94A3B8]",
            ring: "focus:ring-[#64748B]",
            bgSoft: "bg-[#64748B]/20",
            textStrong: "text-[#1E3A5F]",
            borderSoft: "border-[#64748B]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: null,
    },
    "gold mario": {
        id: "gold_mario",
        name: "Gold Mario",
        type: "Pesante",
        description: "La versione dorata di Mario. Raro e ambito, combina velocità e stile irresistibili.",
        colors: { primary: "#EAB308", secondary: "#713F12", accent: "#FEF9C3", bgDark: "#1A1000", bgLight: "#FEFCE8" },
        tailwind: {
            bg: "bg-[#EAB308]",
            text: "text-[#EAB308]",
            border: "border-[#EAB308]",
            badge: "bg-[#EAB308]/15 text-[#713F12] dark:bg-[#EAB308]/20 dark:text-[#FDE047]",
            ring: "focus:ring-[#EAB308]",
            bgSoft: "bg-[#EAB308]/20",
            textStrong: "text-[#713F12]",
            borderSoft: "border-[#EAB308]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: null,
    },
    "pink gold peach": {
        id: "pink_gold_peach",
        name: "Pink Gold Peach",
        type: "Pesante",
        description: "Peach in metallo rosato scintillante. Peso elevato con la grazia inconfondibile della principessa.",
        colors: { primary: "#EC4899", secondary: "#831843", accent: "#FDF2F8", bgDark: "#1A0012", bgLight: "#FDF2F8" },
        tailwind: {
            bg: "bg-[#EC4899]",
            text: "text-[#EC4899]",
            border: "border-[#EC4899]",
            badge: "bg-[#EC4899]/15 text-[#831843] dark:bg-[#EC4899]/20 dark:text-[#F472B6]",
            ring: "focus:ring-[#EC4899]",
            bgSoft: "bg-[#EC4899]/20",
            textStrong: "text-[#831843]",
            borderSoft: "border-[#EC4899]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },
    birdo: {
        id: "birdo",
        name: "Birdo",
        type: "Medio",
        description: "Controllo eccellente e trazione superiore. Una guida sofisticata con carattere.",
        colors: { primary: "#EC4899", secondary: "#BE185D", accent: "#FDF2F8", bgDark: "#1A0012", bgLight: "#FCE7F3" },
        tailwind: {
            bg: "bg-[#EC4899]",
            text: "text-[#EC4899]",
            border: "border-[#EC4899]",
            badge: "bg-[#EC4899]/15 text-[#BE185D] dark:bg-[#EC4899]/20 dark:text-[#F472B6]",
            ring: "focus:ring-[#EC4899]",
            bgSoft: "bg-[#EC4899]/20",
            textStrong: "text-[#BE185D]",
            borderSoft: "border-[#EC4899]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },
    pauline: {
        id: "pauline",
        name: "Pauline",
        type: "Medio",
        description: "La sindaca di New York in pista. Carisma e stile al massimo livello.",
        colors: { primary: "#DC2626", secondary: "#7C2D12", accent: "#FEF9C3", bgDark: "#1A0000", bgLight: "#FEF2F2" },
        tailwind: {
            bg: "bg-[#DC2626]",
            text: "text-[#DC2626]",
            border: "border-[#DC2626]",
            badge: "bg-[#DC2626]/15 text-[#7C2D12] dark:bg-[#DC2626]/20 dark:text-[#F87171]",
            ring: "focus:ring-[#DC2626]",
            bgSoft: "bg-[#DC2626]/20",
            textStrong: "text-[#7C2D12]",
            borderSoft: "border-[#DC2626]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: null,
    },
    "diddy kong": {
        id: "diddy_kong",
        name: "Diddy Kong",
        type: "Pesante",
        description: "L'amico di DK: vivace e veloce. Ottimo equilibrio tra peso e agilità.",
        colors: { primary: "#DC2626", secondary: "#6B3A1F", accent: "#FEF3C7", bgDark: "#1A0000", bgLight: "#FEF2F2" },
        tailwind: {
            bg: "bg-[#DC2626]",
            text: "text-[#DC2626]",
            border: "border-[#DC2626]",
            badge: "bg-[#DC2626]/15 text-[#6B3A1F] dark:bg-[#DC2626]/20 dark:text-[#FCA5A5]",
            ring: "focus:ring-[#DC2626]",
            bgSoft: "bg-[#DC2626]/20",
            textStrong: "text-[#6B3A1F]",
            borderSoft: "border-[#DC2626]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: null,
    },
    "funky kong": {
        id: "funky_kong",
        name: "Funky Kong",
        type: "Pesante",
        description: "Il Kong più cool della pista. Velocità di punta eccezionale, meta del meta-game.",
        colors: { primary: "#2563EB", secondary: "#1E3A8A", accent: "#FEF9C3", bgDark: "#0A0F25", bgLight: "#EFF6FF" },
        tailwind: {
            bg: "bg-[#2563EB]",
            text: "text-[#2563EB]",
            border: "border-[#2563EB]",
            badge: "bg-[#2563EB]/15 text-[#1E3A8A] dark:bg-[#2563EB]/20 dark:text-[#60A5FA]",
            ring: "focus:ring-[#2563EB]",
            bgSoft: "bg-[#2563EB]/20",
            textStrong: "text-[#1E3A8A]",
            borderSoft: "border-[#2563EB]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: null,
    },
    "koopa troopa": {
        id: "koopa_troopa",
        name: "Koopa Troopa",
        type: "Leggero",
        description: "Piccolo soldato Koopa: accelerazione fulminea e grande maneggevolezza in curva.",
        colors: { primary: "#16A34A", secondary: "#14532D", accent: "#F0FDF4", bgDark: "#052E16", bgLight: "#F0FDF4" },
        tailwind: {
            bg: "bg-[#16A34A]",
            text: "text-[#16A34A]",
            border: "border-[#16A34A]",
            badge: "bg-[#16A34A]/15 text-[#14532D] dark:bg-[#16A34A]/20 dark:text-[#4ADE80]",
            ring: "focus:ring-[#16A34A]",
            bgSoft: "bg-[#16A34A]/20",
            textStrong: "text-[#14532D]",
            borderSoft: "border-[#16A34A]/20",
        },
        animationClass: "animate-drift-fast",
        assets: null,
    },
    "shy guy": {
        id: "shy_guy",
        name: "Shy Guy",
        type: "Leggero",
        description: "Misterioso e agile. Leggerissimo con una trazione sorprendente per la sua statura.",
        colors: { primary: "#EF4444", secondary: "#7F1D1D", accent: "#FFF1F2", bgDark: "#1A0000", bgLight: "#FEF2F2" },
        tailwind: {
            bg: "bg-[#EF4444]",
            text: "text-[#EF4444]",
            border: "border-[#EF4444]",
            badge: "bg-[#EF4444]/15 text-[#7F1D1D] dark:bg-[#EF4444]/20 dark:text-[#F87171]",
            ring: "focus:ring-[#EF4444]",
            bgSoft: "bg-[#EF4444]/20",
            textStrong: "text-[#7F1D1D]",
            borderSoft: "border-[#EF4444]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: null,
    },
    lakitu: {
        id: "lakitu",
        name: "Lakitu",
        type: "Leggero",
        description: "Fluttua sopra la pista sulla sua nuvola. Controllo eccellente e grande agilità.",
        colors: { primary: "#0EA5E9", secondary: "#0C4A6E", accent: "#F0F9FF", bgDark: "#082F49", bgLight: "#F0F9FF" },
        tailwind: {
            bg: "bg-[#0EA5E9]",
            text: "text-[#0EA5E9]",
            border: "border-[#0EA5E9]",
            badge: "bg-[#0EA5E9]/15 text-[#0C4A6E] dark:bg-[#0EA5E9]/20 dark:text-[#38BDF8]",
            ring: "focus:ring-[#0EA5E9]",
            bgSoft: "bg-[#0EA5E9]/20",
            textStrong: "text-[#0C4A6E]",
            borderSoft: "border-[#0EA5E9]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },
    toadette: {
        id: "toadette",
        name: "Toadette",
        type: "Leggero",
        description: "L'amica di Toad: accelerazione ancora più esplosiva, padrona delle traiettorie strette.",
        colors: { primary: "#DB2777", secondary: "#831843", accent: "#FDF2F8", bgDark: "#1A0012", bgLight: "#FCE7F3" },
        tailwind: {
            bg: "bg-[#DB2777]",
            text: "text-[#DB2777]",
            border: "border-[#DB2777]",
            badge: "bg-[#DB2777]/15 text-[#831843] dark:bg-[#DB2777]/20 dark:text-[#F472B6]",
            ring: "focus:ring-[#DB2777]",
            bgSoft: "bg-[#DB2777]/20",
            textStrong: "text-[#831843]",
            borderSoft: "border-[#DB2777]/20",
        },
        animationClass: "animate-drift-fast",
        assets: null,
    },
    "inkling girl": {
        id: "inkling_girl",
        name: "Inkling Girl",
        type: "Leggero",
        description: "Dal mondo di Splatoon: colorata e scattante. Drift fluido con reattività da campionessa.",
        colors: { primary: "#F97316", secondary: "#9A3412", accent: "#FFF7ED", bgDark: "#1C0A00", bgLight: "#FFF7ED" },
        tailwind: {
            bg: "bg-[#F97316]",
            text: "text-[#F97316]",
            border: "border-[#F97316]",
            badge: "bg-[#F97316]/15 text-[#9A3412] dark:bg-[#F97316]/20 dark:text-[#FB923C]",
            ring: "focus:ring-[#F97316]",
            bgSoft: "bg-[#F97316]/20",
            textStrong: "text-[#9A3412]",
            borderSoft: "border-[#F97316]/20",
        },
        animationClass: "animate-drift-fast",
        assets: null,
    },
    "inkling boy": {
        id: "inkling_boy",
        name: "Inkling Boy",
        type: "Leggero",
        description: "Dal mondo di Splatoon: esplosivo e imprevedibile. Controllo preciso ad alta velocità.",
        colors: { primary: "#6366F1", secondary: "#3730A3", accent: "#EEF2FF", bgDark: "#0E0B2E", bgLight: "#EEF2FF" },
        tailwind: {
            bg: "bg-[#6366F1]",
            text: "text-[#6366F1]",
            border: "border-[#6366F1]",
            badge: "bg-[#6366F1]/15 text-[#3730A3] dark:bg-[#6366F1]/20 dark:text-[#A5B4FC]",
            ring: "focus:ring-[#6366F1]",
            bgSoft: "bg-[#6366F1]/20",
            textStrong: "text-[#3730A3]",
            borderSoft: "border-[#6366F1]/20",
        },
        animationClass: "animate-drift-fast",
        assets: null,
    },
    link: {
        id: "link",
        name: "Link",
        type: "Medio",
        description: "L'eroe di Hyrule arriva in pista. Bilanciato e agile, degno del suo leggendario status.",
        colors: { primary: "#16A34A", secondary: "#713F12", accent: "#FEF9C3", bgDark: "#052E16", bgLight: "#F0FDF4" },
        tailwind: {
            bg: "bg-[#16A34A]",
            text: "text-[#16A34A]",
            border: "border-[#16A34A]",
            badge: "bg-[#16A34A]/15 text-[#713F12] dark:bg-[#16A34A]/20 dark:text-[#4ADE80]",
            ring: "focus:ring-[#16A34A]",
            bgSoft: "bg-[#16A34A]/20",
            textStrong: "text-[#713F12]",
            borderSoft: "border-[#16A34A]/20",
        },
        animationClass: "animate-bounce-balanced",
        assets: null,
    },
    isabelle: {
        id: "isabelle",
        name: "Isabelle",
        type: "Medio",
        description: "La segretaria di Animal Crossing: garbata in pista ma sorprendentemente competitiva.",
        colors: { primary: "#F59E0B", secondary: "#78350F", accent: "#FFFBEB", bgDark: "#1C1000", bgLight: "#FFFBEB" },
        tailwind: {
            bg: "bg-[#F59E0B]",
            text: "text-[#F59E0B]",
            border: "border-[#F59E0B]",
            badge: "bg-[#F59E0B]/15 text-[#78350F] dark:bg-[#F59E0B]/20 dark:text-[#FCD34D]",
            ring: "focus:ring-[#F59E0B]",
            bgSoft: "bg-[#F59E0B]/20",
            textStrong: "text-[#78350F]",
            borderSoft: "border-[#F59E0B]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },
    kamek: {
        id: "kamek",
        name: "Kamek",
        type: "Medio",
        description: "Il mago koopa volante. Maneggevole e imprevedibile, lancia magie su ogni curva.",
        colors: { primary: "#4F46E5", secondary: "#1E1B4B", accent: "#EEF2FF", bgDark: "#0E0B2E", bgLight: "#EEF2FF" },
        tailwind: {
            bg: "bg-[#4F46E5]",
            text: "text-[#4F46E5]",
            border: "border-[#4F46E5]",
            badge: "bg-[#4F46E5]/15 text-[#1E1B4B] dark:bg-[#4F46E5]/20 dark:text-[#A5B4FC]",
            ring: "focus:ring-[#4F46E5]",
            bgSoft: "bg-[#4F46E5]/20",
            textStrong: "text-[#1E1B4B]",
            borderSoft: "border-[#4F46E5]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },
    wiggler: {
        id: "wiggler",
        name: "Wiggler",
        type: "Pesante",
        description: "Il bruco colorato e pesante. Lento ad accelerare ma inarrestabile una volta in velocità.",
        colors: { primary: "#84CC16", secondary: "#365314", accent: "#F7FEE7", bgDark: "#0F2000", bgLight: "#F7FEE7" },
        tailwind: {
            bg: "bg-[#84CC16]",
            text: "text-[#84CC16]",
            border: "border-[#84CC16]",
            badge: "bg-[#84CC16]/15 text-[#365314] dark:bg-[#84CC16]/20 dark:text-[#BEF264]",
            ring: "focus:ring-[#84CC16]",
            bgSoft: "bg-[#84CC16]/20",
            textStrong: "text-[#365314]",
            borderSoft: "border-[#84CC16]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: null,
    },
    "petey piranha": {
        id: "petey_piranha",
        name: "Petey Piranha",
        type: "Pesante",
        description: "Il re delle Piante Piranha: enorme e feroce. Velocità brutale con zero riguardo per gli avversari.",
        colors: { primary: "#15803D", secondary: "#14532D", accent: "#DCFCE7", bgDark: "#052E16", bgLight: "#F0FDF4" },
        tailwind: {
            bg: "bg-[#15803D]",
            text: "text-[#15803D]",
            border: "border-[#15803D]",
            badge: "bg-[#15803D]/15 text-[#14532D] dark:bg-[#15803D]/20 dark:text-[#4ADE80]",
            ring: "focus:ring-[#15803D]",
            bgSoft: "bg-[#15803D]/20",
            textStrong: "text-[#14532D]",
            borderSoft: "border-[#15803D]/20",
        },
        animationClass: "animate-heavy-shake",
        assets: null,
    },
    "baby mario": {
        id: "baby_mario",
        name: "Baby Mario",
        type: "Leggero",
        description: "La versione baby di Mario: ultraleggero con un'accelerazione istantanea.",
        colors: { primary: "#E52521", secondary: "#0066CC", accent: "#FEE2E2", bgDark: "#1A0000", bgLight: "#FEE2E2" },
        tailwind: {
            bg: "bg-[#E52521]",
            text: "text-[#E52521]",
            border: "border-[#E52521]",
            badge: "bg-[#E52521]/15 text-[#0066CC] dark:bg-[#E52521]/20 dark:text-[#FCA5A5]",
            ring: "focus:ring-[#E52521]",
            bgSoft: "bg-[#E52521]/20",
            textStrong: "text-[#0066CC]",
            borderSoft: "border-[#E52521]/20",
        },
        animationClass: "animate-drift-fast",
        assets: null,
    },
    "baby luigi": {
        id: "baby_luigi",
        name: "Baby Luigi",
        type: "Leggero",
        description: "Il fratellino verde nella culla: reattivo e scattante come pochi.",
        colors: { primary: "#00B239", secondary: "#001B44", accent: "#DCFCE7", bgDark: "#0B150F", bgLight: "#DCFCE7" },
        tailwind: {
            bg: "bg-[#00B239]",
            text: "text-[#00B239]",
            border: "border-[#00B239]",
            badge: "bg-[#00B239]/15 text-[#001B44] dark:bg-[#00B239]/20 dark:text-[#4ADE80]",
            ring: "focus:ring-[#00B239]",
            bgSoft: "bg-[#00B239]/20",
            textStrong: "text-[#001B44]",
            borderSoft: "border-[#00B239]/20",
        },
        animationClass: "animate-drift-fast",
        assets: null,
    },
    "baby peach": {
        id: "baby_peach",
        name: "Baby Peach",
        type: "Leggero",
        description: "La principessa in versione mini: delicata ma incredibilmente veloce in accelerazione.",
        colors: { primary: "#FBCFE8", secondary: "#9D174D", accent: "#FDF2F8", bgDark: "#1A0012", bgLight: "#FDF2F8" },
        tailwind: {
            bg: "bg-[#FBCFE8]",
            text: "text-[#FBCFE8]",
            border: "border-[#FBCFE8]",
            badge: "bg-[#FBCFE8]/15 text-[#9D174D] dark:bg-[#FBCFE8]/20 dark:text-[#F9A8D4]",
            ring: "focus:ring-[#FBCFE8]",
            bgSoft: "bg-[#FBCFE8]/20",
            textStrong: "text-[#9D174D]",
            borderSoft: "border-[#FBCFE8]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },
    "baby daisy": {
        id: "baby_daisy",
        name: "Baby Daisy",
        type: "Leggero",
        description: "Giocosa e velocissima. La più energica tra i baby, ottima sulle piste tortuose.",
        colors: { primary: "#FDE68A", secondary: "#92400E", accent: "#FFFBEB", bgDark: "#1C1000", bgLight: "#FFFBEB" },
        tailwind: {
            bg: "bg-[#FDE68A]",
            text: "text-[#FDE68A]",
            border: "border-[#FDE68A]",
            badge: "bg-[#FDE68A]/15 text-[#92400E] dark:bg-[#FDE68A]/20 dark:text-[#FCD34D]",
            ring: "focus:ring-[#FDE68A]",
            bgSoft: "bg-[#FDE68A]/20",
            textStrong: "text-[#92400E]",
            borderSoft: "border-[#FDE68A]/20",
        },
        animationClass: "animate-drift-fast",
        assets: null,
    },
    "baby rosalina": {
        id: "baby_rosalina",
        name: "Baby Rosalina",
        type: "Leggero",
        description: "La piccola custode delle stelle. Maneggevolezza impeccabile e guida stellare.",
        colors: { primary: "#BAE6FD", secondary: "#0C4A6E", accent: "#F0F9FF", bgDark: "#082F49", bgLight: "#F0F9FF" },
        tailwind: {
            bg: "bg-[#BAE6FD]",
            text: "text-[#BAE6FD]",
            border: "border-[#BAE6FD]",
            badge: "bg-[#BAE6FD]/15 text-[#0C4A6E] dark:bg-[#BAE6FD]/20 dark:text-[#7DD3FC]",
            ring: "focus:ring-[#BAE6FD]",
            bgSoft: "bg-[#BAE6FD]/20",
            textStrong: "text-[#0C4A6E]",
            borderSoft: "border-[#BAE6FD]/20",
        },
        animationClass: "animate-float-elegant",
        assets: null,
    },

    // ── Varianti Yoshi ───────────────────────────────────────────────────────
    "yoshi rosso":     { id: "yoshi_rosso",     name: "Yoshi Rosso",     type: "Medio",   description: "La variante rossa di Yoshi. Stesso stile, colore di fuoco.",              colors: { primary: "#DC2626", secondary: "#7F1D1D", accent: "#FEE2E2", bgDark: "#1A0000", bgLight: "#FEE2E2" }, tailwind: { bg: "bg-[#DC2626]", text: "text-[#DC2626]", border: "border-[#DC2626]", badge: "bg-[#DC2626]/15 text-[#7F1D1D] dark:bg-[#DC2626]/20 dark:text-[#FCA5A5]", ring: "focus:ring-[#DC2626]", bgSoft: "bg-[#DC2626]/20", textStrong: "text-[#7F1D1D]", borderSoft: "border-[#DC2626]/20" }, animationClass: "animate-drift-fast", assets: null },
    "yoshi blu":       { id: "yoshi_blu",       name: "Yoshi Blu",       type: "Medio",   description: "La variante blu di Yoshi. Freddo come il ghiaccio, veloce come il vento.", colors: { primary: "#2563EB", secondary: "#1E3A8A", accent: "#EFF6FF", bgDark: "#0A0F25", bgLight: "#EFF6FF" }, tailwind: { bg: "bg-[#2563EB]", text: "text-[#2563EB]", border: "border-[#2563EB]", badge: "bg-[#2563EB]/15 text-[#1E3A8A] dark:bg-[#2563EB]/20 dark:text-[#60A5FA]", ring: "focus:ring-[#2563EB]", bgSoft: "bg-[#2563EB]/20", textStrong: "text-[#1E3A8A]", borderSoft: "border-[#2563EB]/20" }, animationClass: "animate-drift-fast", assets: null },
    "yoshi rosa":      { id: "yoshi_rosa",      name: "Yoshi Rosa",      type: "Medio",   description: "La variante rosa di Yoshi. Dolce nell'aspetto, deciso in pista.",          colors: { primary: "#EC4899", secondary: "#831843", accent: "#FDF2F8", bgDark: "#1A0012", bgLight: "#FDF2F8" }, tailwind: { bg: "bg-[#EC4899]", text: "text-[#EC4899]", border: "border-[#EC4899]", badge: "bg-[#EC4899]/15 text-[#831843] dark:bg-[#EC4899]/20 dark:text-[#F472B6]", ring: "focus:ring-[#EC4899]", bgSoft: "bg-[#EC4899]/20", textStrong: "text-[#831843]", borderSoft: "border-[#EC4899]/20" }, animationClass: "animate-float-elegant", assets: null },
    "yoshi arancione": { id: "yoshi_arancione", name: "Yoshi Arancione", type: "Medio",   description: "La variante arancione di Yoshi. Energico e imprevedibile.",                colors: { primary: "#F97316", secondary: "#7C2D12", accent: "#FFF7ED", bgDark: "#1C0A00", bgLight: "#FFF7ED" }, tailwind: { bg: "bg-[#F97316]", text: "text-[#F97316]", border: "border-[#F97316]", badge: "bg-[#F97316]/15 text-[#7C2D12] dark:bg-[#F97316]/20 dark:text-[#FB923C]", ring: "focus:ring-[#F97316]", bgSoft: "bg-[#F97316]/20", textStrong: "text-[#7C2D12]", borderSoft: "border-[#F97316]/20" }, animationClass: "animate-drift-fast", assets: null },
    "yoshi azzurro":   { id: "yoshi_azzurro",   name: "Yoshi Azzurro",   type: "Medio",   description: "La variante azzurra di Yoshi. Sereno come il cielo, rapido come il fulmine.", colors: { primary: "#38BDF8", secondary: "#0C4A6E", accent: "#F0F9FF", bgDark: "#082F49", bgLight: "#F0F9FF" }, tailwind: { bg: "bg-[#38BDF8]", text: "text-[#38BDF8]", border: "border-[#38BDF8]", badge: "bg-[#38BDF8]/15 text-[#0C4A6E] dark:bg-[#38BDF8]/20 dark:text-[#7DD3FC]", ring: "focus:ring-[#38BDF8]", bgSoft: "bg-[#38BDF8]/20", textStrong: "text-[#0C4A6E]", borderSoft: "border-[#38BDF8]/20" }, animationClass: "animate-drift-fast", assets: null },
    "yoshi giallo":    { id: "yoshi_giallo",    name: "Yoshi Giallo",    type: "Medio",   description: "La variante gialla di Yoshi. Solare e vivace, difficile da battere.",     colors: { primary: "#EAB308", secondary: "#713F12", accent: "#FEFCE8", bgDark: "#1A1000", bgLight: "#FEFCE8" }, tailwind: { bg: "bg-[#EAB308]", text: "text-[#EAB308]", border: "border-[#EAB308]", badge: "bg-[#EAB308]/15 text-[#713F12] dark:bg-[#EAB308]/20 dark:text-[#FDE047]", ring: "focus:ring-[#EAB308]", bgSoft: "bg-[#EAB308]/20", textStrong: "text-[#713F12]", borderSoft: "border-[#EAB308]/20" }, animationClass: "animate-bounce-balanced", assets: null },
    "yoshi nero":      { id: "yoshi_nero",      name: "Yoshi Nero",      type: "Medio",   description: "La variante nera di Yoshi. Misterioso e temibile, domina la notte.",      colors: { primary: "#374151", secondary: "#111827", accent: "#F9FAFB", bgDark: "#030712", bgLight: "#F9FAFB" }, tailwind: { bg: "bg-[#374151]", text: "text-[#374151]", border: "border-[#374151]", badge: "bg-[#374151]/15 text-[#111827] dark:bg-[#374151]/20 dark:text-[#9CA3AF]", ring: "focus:ring-[#374151]", bgSoft: "bg-[#374151]/20", textStrong: "text-[#111827]", borderSoft: "border-[#374151]/20" }, animationClass: "animate-heavy-shake", assets: null },
    "yoshi bianco":    { id: "yoshi_bianco",    name: "Yoshi Bianco",    type: "Medio",   description: "La variante bianca di Yoshi. Pura eleganza ad alta velocità.",            colors: { primary: "#D1D5DB", secondary: "#374151", accent: "#F9FAFB", bgDark: "#111827", bgLight: "#F9FAFB" }, tailwind: { bg: "bg-[#D1D5DB]", text: "text-[#D1D5DB]", border: "border-[#D1D5DB]", badge: "bg-[#D1D5DB]/15 text-[#374151] dark:bg-[#D1D5DB]/20 dark:text-[#E5E7EB]", ring: "focus:ring-[#D1D5DB]", bgSoft: "bg-[#D1D5DB]/20", textStrong: "text-[#374151]", borderSoft: "border-[#D1D5DB]/20" }, animationClass: "animate-float-elegant", assets: null },

    // ── Varianti Shy Guy ─────────────────────────────────────────────────────
    "shy guy blu":     { id: "shy_guy_blu",     name: "Shy Guy Blu",     type: "Leggero", description: "Il Tipo Timido in blu. Freddo e preciso, difficile da superare.",           colors: { primary: "#2563EB", secondary: "#1E3A8A", accent: "#EFF6FF", bgDark: "#0A0F25", bgLight: "#EFF6FF" }, tailwind: { bg: "bg-[#2563EB]", text: "text-[#2563EB]", border: "border-[#2563EB]", badge: "bg-[#2563EB]/15 text-[#1E3A8A] dark:bg-[#2563EB]/20 dark:text-[#60A5FA]", ring: "focus:ring-[#2563EB]", bgSoft: "bg-[#2563EB]/20", textStrong: "text-[#1E3A8A]", borderSoft: "border-[#2563EB]/20" }, animationClass: "animate-bounce-balanced", assets: null },
    "shy guy giallo":  { id: "shy_guy_giallo",  name: "Shy Guy Giallo",  type: "Leggero", description: "Il Tipo Timido in giallo. Brillante e sorprendentemente agile.",             colors: { primary: "#EAB308", secondary: "#713F12", accent: "#FEFCE8", bgDark: "#1A1000", bgLight: "#FEFCE8" }, tailwind: { bg: "bg-[#EAB308]", text: "text-[#EAB308]", border: "border-[#EAB308]", badge: "bg-[#EAB308]/15 text-[#713F12] dark:bg-[#EAB308]/20 dark:text-[#FDE047]", ring: "focus:ring-[#EAB308]", bgSoft: "bg-[#EAB308]/20", textStrong: "text-[#713F12]", borderSoft: "border-[#EAB308]/20" }, animationClass: "animate-bounce-balanced", assets: null },
    "shy guy verde":   { id: "shy_guy_verde",   name: "Shy Guy Verde",   type: "Leggero", description: "Il Tipo Timido in verde. Mimetico e difficile da individuare in pista.",    colors: { primary: "#16A34A", secondary: "#14532D", accent: "#F0FDF4", bgDark: "#052E16", bgLight: "#F0FDF4" }, tailwind: { bg: "bg-[#16A34A]", text: "text-[#16A34A]", border: "border-[#16A34A]", badge: "bg-[#16A34A]/15 text-[#14532D] dark:bg-[#16A34A]/20 dark:text-[#4ADE80]", ring: "focus:ring-[#16A34A]", bgSoft: "bg-[#16A34A]/20", textStrong: "text-[#14532D]", borderSoft: "border-[#16A34A]/20" }, animationClass: "animate-drift-fast", assets: null },
    "shy guy rosa":    { id: "shy_guy_rosa",    name: "Shy Guy Rosa",    type: "Leggero", description: "Il Tipo Timido in rosa. Timido nell'aspetto, spietato in pista.",            colors: { primary: "#EC4899", secondary: "#831843", accent: "#FDF2F8", bgDark: "#1A0012", bgLight: "#FDF2F8" }, tailwind: { bg: "bg-[#EC4899]", text: "text-[#EC4899]", border: "border-[#EC4899]", badge: "bg-[#EC4899]/15 text-[#831843] dark:bg-[#EC4899]/20 dark:text-[#F472B6]", ring: "focus:ring-[#EC4899]", bgSoft: "bg-[#EC4899]/20", textStrong: "text-[#831843]", borderSoft: "border-[#EC4899]/20" }, animationClass: "animate-float-elegant", assets: null },
    "shy guy azzurro": { id: "shy_guy_azzurro", name: "Shy Guy Azzurro", type: "Leggero", description: "Il Tipo Timido in azzurro. Leggero come l'aria, veloce come il suono.",     colors: { primary: "#38BDF8", secondary: "#0C4A6E", accent: "#F0F9FF", bgDark: "#082F49", bgLight: "#F0F9FF" }, tailwind: { bg: "bg-[#38BDF8]", text: "text-[#38BDF8]", border: "border-[#38BDF8]", badge: "bg-[#38BDF8]/15 text-[#0C4A6E] dark:bg-[#38BDF8]/20 dark:text-[#7DD3FC]", ring: "focus:ring-[#38BDF8]", bgSoft: "bg-[#38BDF8]/20", textStrong: "text-[#0C4A6E]", borderSoft: "border-[#38BDF8]/20" }, animationClass: "animate-drift-fast", assets: null },
    "shy guy bianco":  { id: "shy_guy_bianco",  name: "Shy Guy Bianco",  type: "Leggero", description: "Il Tipo Timido in bianco. Puro ed enigmatico, la maschera nasconde un campione.", colors: { primary: "#E5E7EB", secondary: "#374151", accent: "#F9FAFB", bgDark: "#111827", bgLight: "#F9FAFB" }, tailwind: { bg: "bg-[#E5E7EB]", text: "text-[#E5E7EB]", border: "border-[#E5E7EB]", badge: "bg-[#E5E7EB]/15 text-[#374151] dark:bg-[#E5E7EB]/20 dark:text-[#D1D5DB]", ring: "focus:ring-[#E5E7EB]", bgSoft: "bg-[#E5E7EB]/20", textStrong: "text-[#374151]", borderSoft: "border-[#E5E7EB]/20" }, animationClass: "animate-float-elegant", assets: null },
    "shy guy nero":    { id: "shy_guy_nero",    name: "Shy Guy Nero",    type: "Leggero", description: "Il Tipo Timido in nero. Oscuro e letale, il più temuto tra i Tipi Timidi.", colors: { primary: "#1F2937", secondary: "#030712", accent: "#F9FAFB", bgDark: "#030712", bgLight: "#F9FAFB" }, tailwind: { bg: "bg-[#1F2937]", text: "text-[#1F2937]", border: "border-[#1F2937]", badge: "bg-[#1F2937]/15 text-[#030712] dark:bg-[#1F2937]/20 dark:text-[#6B7280]", ring: "focus:ring-[#1F2937]", bgSoft: "bg-[#1F2937]/20", textStrong: "text-[#030712]", borderSoft: "border-[#1F2937]/20" }, animationClass: "animate-heavy-shake", assets: null },

}

const DEFAULT_THEME = {
    name: 'standard',
    label: 'Tema standard',
    accent: '#22c55e',
    accentSoft: 'rgba(34, 197, 94, 0.18)',
    accentStrong: '#166534',
    accentGlow: 'rgba(34, 197, 94, 0.32)',
    pageBackground: 'linear-gradient(180deg, #f8fafc 0%, #eff6ff 100%)',
    pageOverlay: 'radial-gradient(circle at top right, rgba(34, 197, 94, 0.12), transparent 42%), radial-gradient(circle at bottom left, rgba(14, 165, 233, 0.1), transparent 34%)',
    cardBackground: 'linear-gradient(135deg, rgba(255, 255, 255, 1), rgba(240, 253, 244, 1))',
    navbarBackground: 'rgba(15, 23, 42, 0.9)',
    border: 'rgba(34, 197, 94, 0.2)',
    textSoft: '#475569',
    textStrong: '#0f172a',
    tailwind: {
        bg: "bg-[#22c55e]",
        text: "text-[#22c55e]",
        border: "border-[#22c55e]",
        badge: "bg-[#22c55e]/15 text-[#16a34a] dark:bg-[#22c55e]/20 dark:text-[#4ade80]",
        ring: "focus:ring-[#22c55e]",
        bgSoft: "bg-[#22c55e]/20",
        textStrong: "text-[#166534]",
        borderSoft: "border-[#22c55e]/20",
    },
    animationClass: null,
    assets: null,
    characterType: null,
    characterDescription: null,
}

const PALETTES = [
    {
        accent: '#06b6d4',
        accentSoft: 'rgba(6, 182, 212, 0.2)',
        accentStrong: '#0e7490',
        accentGlow: 'rgba(6, 182, 212, 0.34)',
        pageBackground: 'linear-gradient(180deg, #ecfeff 0%, #f8fafc 100%)',
        pageOverlay: 'radial-gradient(circle at top right, rgba(6, 182, 212, 0.14), transparent 40%), radial-gradient(circle at bottom left, rgba(14, 116, 144, 0.14), transparent 34%)',
        cardBackground: 'linear-gradient(135deg, rgba(236, 254, 255, 1), rgba(255, 255, 255, 1))',
        navbarBackground: 'rgba(8, 47, 73, 0.9)',
        border: 'rgba(6, 182, 212, 0.22)',
        textSoft: '#155e75',
        textStrong: '#082f49',
        tailwind: {
            bg: "bg-[#06b6d4]",
            text: "text-[#06b6d4]",
            border: "border-[#06b6d4]",
            badge: "bg-[#06b6d4]/15 text-[#0e7490] dark:bg-[#06b6d4]/20 dark:text-[#22d3ee]",
            ring: "focus:ring-[#06b6d4]",
            bgSoft: "bg-[#06b6d4]/20",
            textStrong: "text-[#0e7490]",
            borderSoft: "border-[#06b6d4]/20",
        },
    },
    {
        accent: '#f97316',
        accentSoft: 'rgba(249, 115, 22, 0.2)',
        accentStrong: '#c2410c',
        accentGlow: 'rgba(249, 115, 22, 0.34)',
        pageBackground: 'linear-gradient(180deg, #fff7ed 0%, #f8fafc 100%)',
        pageOverlay: 'radial-gradient(circle at top right, rgba(249, 115, 22, 0.16), transparent 40%), radial-gradient(circle at bottom left, rgba(194, 65, 12, 0.12), transparent 34%)',
        cardBackground: 'linear-gradient(135deg, rgba(255, 247, 237, 1), rgba(255, 255, 255, 1))',
        navbarBackground: 'rgba(67, 20, 7, 0.92)',
        border: 'rgba(249, 115, 22, 0.22)',
        textSoft: '#9a3412',
        textStrong: '#431407',
        tailwind: {
            bg: "bg-[#f97316]",
            text: "text-[#f97316]",
            border: "border-[#f97316]",
            badge: "bg-[#f97316]/15 text-[#c2410c] dark:bg-[#f97316]/20 dark:text-[#fb923c]",
            ring: "focus:ring-[#f97316]",
            bgSoft: "bg-[#f97316]/20",
            textStrong: "text-[#c2410c]",
            borderSoft: "border-[#f97316]/20",
        },
    },
    {
        accent: '#8b5cf6',
        accentSoft: 'rgba(139, 92, 246, 0.2)',
        accentStrong: '#6d28d9',
        accentGlow: 'rgba(139, 92, 246, 0.34)',
        pageBackground: 'linear-gradient(180deg, #faf5ff 0%, #f8fafc 100%)',
        pageOverlay: 'radial-gradient(circle at top right, rgba(139, 92, 246, 0.16), transparent 40%), radial-gradient(circle at bottom left, rgba(109, 40, 217, 0.12), transparent 34%)',
        cardBackground: 'linear-gradient(135deg, rgba(250, 245, 255, 1), rgba(255, 255, 255, 1))',
        navbarBackground: 'rgba(46, 16, 101, 0.92)',
        border: 'rgba(139, 92, 246, 0.22)',
        textSoft: '#7e22ce',
        textStrong: '#3b0764',
        tailwind: {
            bg: "bg-[#8b5cf6]",
            text: "text-[#8b5cf6]",
            border: "border-[#8b5cf6]",
            badge: "bg-[#8b5cf6]/15 text-[#6d28d9] dark:bg-[#8b5cf6]/20 dark:text-[#a78bfa]",
            ring: "focus:ring-[#8b5cf6]",
            bgSoft: "bg-[#8b5cf6]/20",
            textStrong: "text-[#6d28d9]",
            borderSoft: "border-[#8b5cf6]/20",
        },
    },
    {
        accent: '#ef4444',
        accentSoft: 'rgba(239, 68, 68, 0.2)',
        accentStrong: '#b91c1c',
        accentGlow: 'rgba(239, 68, 68, 0.34)',
        pageBackground: 'linear-gradient(180deg, #fff1f2 0%, #f8fafc 100%)',
        pageOverlay: 'radial-gradient(circle at top right, rgba(239, 68, 68, 0.14), transparent 40%), radial-gradient(circle at bottom left, rgba(185, 28, 28, 0.12), transparent 34%)',
        cardBackground: 'linear-gradient(135deg, rgba(255, 241, 242, 1), rgba(255, 255, 255, 1))',
        navbarBackground: 'rgba(69, 10, 10, 0.92)',
        border: 'rgba(239, 68, 68, 0.22)',
        textSoft: '#b91c1c',
        textStrong: '#450a0a',
        tailwind: {
            bg: "bg-[#ef4444]",
            text: "text-[#ef4444]",
            border: "border-[#ef4444]",
            badge: "bg-[#ef4444]/15 text-[#b91c1c] dark:bg-[#ef4444]/20 dark:text-[#f87171]",
            ring: "focus:ring-[#ef4444]",
            bgSoft: "bg-[#ef4444]/20",
            textStrong: "text-[#b91c1c]",
            borderSoft: "border-[#ef4444]/20",
        },
    },
    {
        accent: '#14b8a6',
        accentSoft: 'rgba(20, 184, 166, 0.2)',
        accentStrong: '#0f766e',
        accentGlow: 'rgba(20, 184, 166, 0.34)',
        pageBackground: 'linear-gradient(180deg, #f0fdfa 0%, #f8fafc 100%)',
        pageOverlay: 'radial-gradient(circle at top right, rgba(20, 184, 166, 0.16), transparent 40%), radial-gradient(circle at bottom left, rgba(15, 118, 110, 0.12), transparent 34%)',
        cardBackground: 'linear-gradient(135deg, rgba(240, 253, 250, 1), rgba(255, 255, 255, 1))',
        navbarBackground: 'rgba(4, 47, 46, 0.92)',
        border: 'rgba(20, 184, 166, 0.22)',
        textSoft: '#0f766e',
        textStrong: '#042f2e',
        tailwind: {
            bg: "bg-[#14b8a6]",
            text: "text-[#14b8a6]",
            border: "border-[#14b8a6]",
            badge: "bg-[#14b8a6]/15 text-[#0f766e] dark:bg-[#14b8a6]/20 dark:text-[#2dd4bf]",
            ring: "focus:ring-[#14b8a6]",
            bgSoft: "bg-[#14b8a6]/20",
            textStrong: "text-[#0f766e]",
            borderSoft: "border-[#14b8a6]/20",
        },
    },
]

const normalizeText = (value) => {
    return (value ?? '')
        .toString()
        .trim()
        .toLowerCase()
}

const hashString = (value) => {
    let hash = 0

    for (let index = 0; index < value.length; index += 1) {
        hash = (hash * 31 + value.charCodeAt(index)) >>> 0
    }

    return hash
}

const DARK_OVERRIDES = {
    pageBackground: 'linear-gradient(180deg, #0f172a 0%, #020617 100%)',
    pageOverlay: 'radial-gradient(circle at top right, rgba(34, 197, 94, 0.08), transparent 42%), radial-gradient(circle at bottom left, rgba(14, 165, 233, 0.06), transparent 34%)',
    cardBackground: 'linear-gradient(135deg, rgba(30, 41, 59, 1), rgba(15, 23, 42, 1))',
    navbarBackground: 'rgba(2, 6, 23, 0.95)',
    border: 'rgba(148, 163, 184, 0.15)',
    textSoft: '#94a3b8',
    textStrong: '#f8fafc',
}

const hexToRgba = (hex, alpha) => {
    const r = parseInt(hex.slice(1, 3), 16)
    const g = parseInt(hex.slice(3, 5), 16)
    const b = parseInt(hex.slice(5, 7), 16)
    return `rgba(${r}, ${g}, ${b}, ${alpha})`
}

// Stessa tinta di hexToRgba(hex, alpha) ma pre-miscelata su una base
// opaca invece di usare la trasparenza reale — le card sopra la foto di
// sfondo fissa della pagina non devono lasciarla trasparire (segnalato
// dall'utente), quindi qui il "peso" della tinta è nel colore risultante,
// non nell'alpha (che resta sempre 1).
const mixHexOverRgb = (hex, alpha, baseRgb) => {
    const r = parseInt(hex.slice(1, 3), 16)
    const g = parseInt(hex.slice(3, 5), 16)
    const b = parseInt(hex.slice(5, 7), 16)
    const [br, bg, bb] = baseRgb
    const mix = (channel, base) => Math.round(channel * alpha + base * (1 - alpha))
    return `rgb(${mix(r, br)}, ${mix(g, bg)}, ${mix(b, bb)})`
}

const mkThemeToPalette = (mkTheme, dark = false) => {
    const { colors } = mkTheme
    const primary = colors.primary
    const secondary = colors.secondary

    if (dark) {
        const darkBg = colors.bgDark
            ? `linear-gradient(180deg, ${colors.bgDark} 0%, #020617 100%)`
            : DARK_OVERRIDES.pageBackground
        return {
            accent: primary,
            accentSoft: hexToRgba(primary, 0.18),
            accentStrong: secondary,
            accentGlow: hexToRgba(primary, 0.32),
            pageBackground: darkBg,
            pageOverlay: DARK_OVERRIDES.pageOverlay,
            cardBackground: `linear-gradient(135deg, ${mixHexOverRgb(primary, 0.10, [30, 41, 59])}, rgb(15, 23, 42))`,
            navbarBackground: hexToRgba(primary, 0.2),
            border: hexToRgba(primary, 0.2),
            textSoft: '#94a3b8',
            textStrong: '#f8fafc',
        }
    }

    const lightBg = colors.bgLight
        ? `linear-gradient(180deg, ${colors.bgLight} 0%, #f8fafc 100%)`
        : `linear-gradient(180deg, ${hexToRgba(primary, 0.06)} 0%, #f8fafc 100%)`

    return {
        accent: primary,
        accentSoft: hexToRgba(primary, 0.18),
        accentStrong: secondary,
        accentGlow: hexToRgba(primary, 0.32),
        pageBackground: lightBg,
        pageOverlay: `radial-gradient(circle at top right, ${hexToRgba(primary, 0.12)}, transparent 42%), radial-gradient(circle at bottom left, ${hexToRgba(secondary, 0.1)}, transparent 34%)`,
        cardBackground: `linear-gradient(135deg, rgb(255, 255, 255), ${mixHexOverRgb(primary, 0.06, [255, 255, 255])})`,
        navbarBackground: 'rgba(15, 23, 42, 0.9)',
        border: hexToRgba(primary, 0.2),
        textSoft: '#475569',
        textStrong: '#0f172a',
    }
}

const toTheme = (palette, characterName, player, dark = false, mkTheme = null) => {
    const base = {
        ...palette,
        characterName,
        teamName: characterName ? `${characterName} Team` : 'Lega Kart Team',
        playerNickname: player?.nickname ?? null,
        avatarUrl: player?.img_url ?? null,
        hasPlayerAvatar: Boolean(player?.img_url),
        isPersonalized: Boolean(characterName),
        tailwind: mkTheme?.tailwind ?? palette.tailwind ?? DEFAULT_THEME.tailwind,
        animationClass: mkTheme?.animationClass ?? null,
        assets: mkTheme?.assets ?? null,
        characterType: mkTheme?.type ?? null,
        characterDescription: mkTheme?.description ?? null,
    }
    if (dark) {
        return {
            ...base,
            ...DARK_OVERRIDES,
            accent: palette.accent,
            accentSoft: palette.accentSoft,
            accentStrong: palette.accentStrong,
            accentGlow: palette.accentGlow,
            tailwind: {
                ...base.tailwind,
                textStrong: 'text-[#f8fafc]',
            },
        }
    }
    return base
}

export const getProfileTheme = (user, charactersById, dark = false) => {
    const player = user?.player ?? null
    const character = player?.favorite_character_id ? charactersById?.get(player.favorite_character_id) ?? null : null
    const normalizedCharacterName = normalizeText(character?.name)

    if (normalizedCharacterName) {
        const mkTheme = MARIO_KART_THEMES[normalizedCharacterName]
        if (mkTheme) {
            const palette = mkThemeToPalette(mkTheme, dark)
            return toTheme(palette, mkTheme.name, player, dark, mkTheme)
        }
    }

    if (!character) {
        return toTheme(DEFAULT_THEME, null, player, dark)
    }

    const palette = PALETTES[hashString(normalizedCharacterName) % PALETTES.length]
    return toTheme(palette, character.name, player, dark)
}
